name: iks_fokino_app
description: Личный кабинет потребителя ИКС-Фокино
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.18.1
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  flutter_masked_text2: ^0.9.1
  sqflite_common_ffi: ^2.2.1 # Для Windows поддержки
  url_launcher: ^6.2.2  # Добавьте эту строку

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/data/demo_data.json # ← Укажите конкретный файл